# Site settings
title: MerDrew
subtitle: Data Specialists
email: merdrew17@gmail.com
description: Home of the experts for all your data needs.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: Houston
state: TX
zip_code:
country: United States of America
phone: (832) 203-7336

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/merdrew
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
